### ISSUE TITLE
Better Portals Not Capability with Rediscovered Mod 

### ISSUE THREAD

**Issue by Klouver-github** [YUNG-GANG/YUNGs-Better-Portals#5]
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$36926/1861094941.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassCastException: com.yungnickyoung.minecraft.betterportals.capability.EntityPortalInfo cannot be cast to com.legacy.rediscovered.capability.IRediscoveredPiglin
	at com.legacy.rediscovered.event.RediscoveredEvents$$Lambda$40081/628330634.accept(Unknown Source) ~[?:?]
	at com.legacy.rediscovered.capability.RediscoveredPiglinCapability.ifPresent(RediscoveredPiglinCapability.java:52) ~[?:1.3.7]
	at com.legacy.rediscovered.event.RediscoveredEvents.onEntityUpdate(RediscoveredEvents.java:414) ~[?:1.3.7]
	at net.minecraftforge.eventbus.ASMEventHandler_3517_RediscoveredEvents_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2066/2060563648.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:331) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:205) ~[?:?]
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1612) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70098_U(LivingEntity.java:2576) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217459_a(ServerWorld.java:638) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:618) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$37861/238319729.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more

**Comment by TLATER** [comment]
Same problem with DoggyTalents, check the linked issue.

**Comment by yungnickyoung** [comment]
Try v0.3.1 to see if it fixes this issue for you.

**Comment by TLATER** [comment]
v0.3.1 fixed the DoggyTalents compat, thank you very much!
